name: Update

#on:
   #schedule:
     #- cron: '0 0 * * *'  # 每天午夜12点执行（UTC）

on:
  workflow_dispatch:
jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update
        run: |
          echo "Hello"
          make adguardhome
          make sing
          make anti-ad
          make clean
          make push
